export const AUTH_COMMON = {
    emailLabel: 'EMAIL ADDRESS',
    emailPlaceholder: 'name@example.com',
    passwordPlaceholder: '••••••••',
    orContinueWith: 'OR CONTINUE WITH',
    googleButton: 'Google',
    continueWithGoogle: 'Continue with Google',
}

export const LOGIN = {
    title: 'Welcome Back',
    description: 'Please enter your details to access your sanctuary.',
    emailLabel: AUTH_COMMON.emailLabel,
    emailPlaceholder: AUTH_COMMON.emailPlaceholder,
    passwordLabel: 'PASSWORD',
    forgotPasswordLink: 'Forgot Password?',
    loginButton: 'Log In',
    loggingInButton: 'Logging in...',
    orContinueWith: AUTH_COMMON.orContinueWith,
    googleButton: AUTH_COMMON.googleButton,
    signupText: `Don't have an account?`,
    signupLink: 'Sign Up',
    hipaaText: 'SECURE HIPAA COMPLIANT CONNECTION',
}

export const SIGNUP = {
    title: 'Create Your Account',
    description: 'Join thousands of patients on their recovery journey. It takes less than a minute.',
    firstNameLabel: 'FIRST NAME',
    firstNamePlaceholder: 'John',
    lastNameLabel: 'LAST NAME',
    lastNamePlaceholder: 'Doe',
    emailLabel: AUTH_COMMON.emailLabel,
    emailPlaceholder: AUTH_COMMON.emailPlaceholder,
    passwordLabel: 'PASSWORD',
    passwordPlaceholder: AUTH_COMMON.passwordPlaceholder,
    confirmPasswordLabel: 'CONFIRM PASSWORD',
    confirmPasswordPlaceholder: AUTH_COMMON.passwordPlaceholder,
    signupButton: 'Create Account',
    signingUpButton: 'Creating account...',
    loginText: 'Already have an account?',
    loginLink: 'Sign In',
    orContinueWith: AUTH_COMMON.orContinueWith,
    googleButton: AUTH_COMMON.googleButton,
}

export const FORGOT_PASSWORD = {
    title: 'Forgot password?',
    description: `Don't worry, it happens to the best of us. Enter the email address associated with your account and we'll send you a link to reset your password.`,
    emailLabel: AUTH_COMMON.emailLabel,
    emailPlaceholder: AUTH_COMMON.emailPlaceholder,
    submitButton: 'Send Reset Link',
    sendingButton: 'Sending...',
    backButton: 'Back to Login',
    checkEmailTitle: 'Check your email',
    checkEmailDesc: `We've sent a password reset link to`,
    supportLink: 'support team',
    supportText: 'If you no longer have access to your email, please contact our',
    supportVerification: 'for identity verification.',
}

export const RESET_PASSWORD = {
    title: 'Create New Password',
    description: 'Choose a secure password to regain access to your recovery dashboard.',
    passwordLabel: 'NEW PASSWORD',
    confirmPasswordLabel: 'CONFIRM NEW PASSWORD',
    passwordPlaceholder: '••••••••',
    minLengthText: 'Min 8 characters',
    specialCharText: 'One special symbol',
    submitButton: 'Reset Password',
    resettingButton: 'Resetting...',
    backButton: 'Back to login',
    troubleText: 'Having trouble?',
    supportLink: 'Contact Health Support',
}
