const INSIGHTS_MILESTONE_TITLE = 'Milestone Reached!'

const INSIGHTS_MILESTONE_DESCRIPTION = 'You\'ve logged 10 consecutive days! Consistency is the foundation of lasting recovery.'

const INSIGHTS_MILESTONE_LEVEL = 'GOLD STREAK LEVEL 1'

const INSIGHTS_PATTERNS_TITLE = 'Behavioral Patterns'

const INSIGHTS_PATTERNS_CORRELATION_LABEL = 'CORRELATION'

const INSIGHTS_PATTERNS_CORRELATION_TITLE = 'Social Interaction vs. Stress'

const INSIGHTS_PATTERNS_CORRELATION_DESCRIPTION = 'You report 22% lower stress levels on days when you participate in community group chats.'

const INSIGHTS_PATTERNS_OBSERVATION_LABEL = 'OBSERVATION'

const INSIGHTS_PATTERNS_OBSERVATION_TITLE = 'Morning Routine Impact'

const INSIGHTS_PATTERNS_OBSERVATION_DESCRIPTION = 'Completing a Daily Check-In before 9:00 AM leads to a 30% higher chance of reaching all daily recovery goals.'

const INSIGHTS_PATTERNS_OBSERVATION_SUCCESS_LABEL = 'SUCCESS RATE WHEN DAILY'

const INSIGHTS_PATTERNS_OBSERVATION_SUCCESS_VALUE = '82%'

const INSIGHTS_PATTERNS_PREDICTION_LABEL = 'AI PREDICTION'

const INSIGHTS_PATTERNS_PREDICTION_TITLE = 'Projected Recovery Path'

const INSIGHTS_PATTERNS_PREDICTION_DESCRIPTION = 'If current adherence maintains, you are on track to increase your range of motion by 8% next week.'

const INSIGHTS_PATTERNS_PREDICTION_BADGE = 'HIGH CONFIDENCE ANALYTICS'

export {
    INSIGHTS_MILESTONE_DESCRIPTION,
    INSIGHTS_MILESTONE_LEVEL,
    INSIGHTS_MILESTONE_TITLE,
    INSIGHTS_PATTERNS_CORRELATION_DESCRIPTION,
    INSIGHTS_PATTERNS_CORRELATION_LABEL,
    INSIGHTS_PATTERNS_CORRELATION_TITLE,
    INSIGHTS_PATTERNS_OBSERVATION_DESCRIPTION,
    INSIGHTS_PATTERNS_OBSERVATION_LABEL,
    INSIGHTS_PATTERNS_OBSERVATION_SUCCESS_LABEL,
    INSIGHTS_PATTERNS_OBSERVATION_SUCCESS_VALUE,
    INSIGHTS_PATTERNS_OBSERVATION_TITLE,
    INSIGHTS_PATTERNS_PREDICTION_BADGE,
    INSIGHTS_PATTERNS_PREDICTION_DESCRIPTION,
    INSIGHTS_PATTERNS_PREDICTION_LABEL,
    INSIGHTS_PATTERNS_PREDICTION_TITLE,
    INSIGHTS_PATTERNS_TITLE,
}
