export const authTexts = {
    common: {
        emailLabel: 'EMAIL ADDRESS',
        emailPlaceholder: 'name@example.com',
        passwordPlaceholder: '••••••••',
        orContinueWith: 'OR CONTINUE WITH',
        googleButton: 'Google',
        continueWithGoogle: 'Continue with Google'
    },
    login: {
        title: 'Welcome Back',
        description: 'Please enter your details to access your sanctuary.',
        emailLabel: 'EMAIL ADDRESS',
        emailPlaceholder: 'name@example.com',
        passwordLabel: 'PASSWORD',
        forgotPasswordLink: 'Forgot Password?',
        loginButton: 'Log In',
        loggingInButton: 'Logging in...',
        orContinueWith: 'OR CONTINUE WITH',
        googleButton: 'Google',
        signupText: `Don't have an account?`,
        signupLink: 'Sign Up',
        hipaaText: 'SECURE HIPAA COMPLIANT CONNECTION'
    },
    signup: {
        title: 'Create Your Account',
        description: 'Join thousands of patients on their recovery journey. It takes less than a minute.',
        firstNameLabel: 'FIRST NAME',
        firstNamePlaceholder: 'John',
        lastNameLabel: 'LAST NAME',
        lastNamePlaceholder: 'Doe',
        emailLabel: 'EMAIL ADDRESS',
        emailPlaceholder: 'name@example.com',
        passwordLabel: 'PASSWORD',
        passwordPlaceholder: '••••••••',
        confirmPasswordLabel: 'CONFIRM PASSWORD',
        confirmPasswordPlaceholder: '••••••••',
        signupButton: 'Create Account',
        signingUpButton: 'Creating account...',
        loginText: 'Already have an account?',
        loginLink: 'Sign In',
        orContinueWith: 'OR CONTINUE WITH',
        googleButton: 'Google'
    },
    forgotPassword: {
        title: 'Forgot password?',
        description: `Don't worry, it happens to the best of us. Enter the email address associated with your account and we'll send you a link to reset your password.`,
        emailLabel: 'EMAIL ADDRESS',
        emailPlaceholder: 'name@example.com',
        submitButton: 'Send Reset Link',
        sendingButton: 'Sending...',
        backButton: 'Back to Login',
        checkEmailTitle: 'Check your email',
        checkEmailDesc: `We've sent a password reset link to`,
        supportLink: 'support team',
        supportText: 'If you no longer have access to your email, please contact our',
        supportVerification: 'for identity verification.'
    },
    resetPassword: {
        title: 'Create New Password',
        description: 'Choose a secure password to regain access to your recovery dashboard.',
        passwordLabel: 'NEW PASSWORD',
        confirmPasswordLabel: 'CONFIRM NEW PASSWORD',
        passwordPlaceholder: '••••••••',
        minLengthText: 'Min 8 characters',
        specialCharText: 'One special symbol',
        submitButton: 'Reset Password',
        resettingButton: 'Resetting...',
        backButton: 'Back to login',
        troubleText: 'Having trouble?',
        supportLink: 'Contact Health Support'
    }
}
